import { useEffect, useMemo, useState } from 'react'
import { buffets } from '../../data/buffets'
import type { Buffet } from '../../types/Buffet'
import { createReviewIssueUrl, emptyReviewDraft, findReviewMatches, REVIEW_DRAFT_KEY, reviewPayload, snapshotFromBuffet, US_STATES, validateReviewDraft, type ReviewDraft } from '../../utilities/reviews'
import { GitHubAccountNotice } from '../Contributions/GitHubAccountNotice'
import { GoonRating } from './GoonRating'

function initialDraft(): ReviewDraft { try { return { ...emptyReviewDraft, ...JSON.parse(localStorage.getItem(REVIEW_DRAFT_KEY) ?? '{}') } } catch { return emptyReviewDraft } }
export function PostReviewForm() {
  const [draft, setDraft] = useState(initialDraft)
  const [showErrors, setShowErrors] = useState(false)
  const selected = buffets.find((b) => b.id === draft.buffetId)
  const matches = useMemo(() => findReviewMatches(draft, buffets), [draft])
  const errors = useMemo(() => validateReviewDraft(draft), [draft])
  const payload = useMemo(() => reviewPayload(draft), [draft])
  const dirty = Object.entries(draft).some(([key, value]) => key !== 'rating' ? Boolean(String(value).trim()) : value !== 0)
  const update = <K extends keyof ReviewDraft>(key: K, value: ReviewDraft[K]) => setDraft((d) => ({ ...d, [key]: value, ...(['name','city','state','address'].includes(key) ? { buffetId: '' } : {}) }))
  const choose = (buffet: Buffet) => setDraft((d) => ({ ...d, buffetId: buffet.id, ...snapshotFromBuffet(buffet) }))
  useEffect(() => { const id = new URLSearchParams(location.search).get('buffet'); const buffet = buffets.find((b) => b.id === id); if (buffet) setDraft((d) => d.buffetId === buffet.id ? d : ({ ...d, buffetId: buffet.id, ...snapshotFromBuffet(buffet) })) }, [])
  useEffect(() => { localStorage.setItem(REVIEW_DRAFT_KEY, JSON.stringify(draft)) }, [draft])
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault() }; addEventListener('beforeunload', warn); return () => removeEventListener('beforeunload', warn) }, [dirty])
  const field = (key: keyof ReviewDraft, label: string, required = false, type = 'text') => <label className="admin-field"><span>{label}{required && <b> *</b>}</span><input type={type} value={String(draft[key])} required={required} onChange={(e) => update(key, e.target.value as never)} aria-invalid={showErrors && Boolean(errors[key])} />{showErrors && errors[key] && <em role="alert">{errors[key]}</em>}</label>
  const clear = () => { if (dirty && !confirm('Clear this review draft?')) return; setDraft(emptyReviewDraft); localStorage.removeItem(REVIEW_DRAFT_KEY); setShowErrors(false) }
  return <main className="admin-page"><header className="admin-header"><div><p>For Two People Presents</p><h1>Post Your Review</h1></div><a href="?reviews=1">Community Reviews</a><a href={location.pathname}>← Back to Map</a></header><div className="admin-layout"><form className="admin-form" noValidate onSubmit={(e) => { e.preventDefault(); setShowErrors(true); if (payload) window.open(createReviewIssueUrl(payload), '_blank', 'noopener,noreferrer') }}><p className="form-intro">Share your experience at a buffet. It does not need to already be on the map.</p><GitHubAccountNotice /><p className="required-note"><b>*</b> Required field. Your draft is saved in this browser.</p><fieldset><legend>Buffet</legend>{field('name','Buffet name',true)}{field('city','City',true)}<label className="admin-field"><span>State <b>*</b></span><select value={draft.state} onChange={(e) => update('state',e.target.value)}><option value="">Select state</option>{US_STATES.map(s => <option key={s}>{s}</option>)}</select>{showErrors && errors.state && <em>{errors.state}</em>}</label>{field('address','Street address',!selected)}{field('postalCode','Postal code')}
      <div className="match-panel admin-wide">{selected ? <><strong>✓ Linked to buffet on map</strong><span>{selected.name} · {selected.city}, {selected.state} · {selected.address}</span><button type="button" onClick={() => setDraft(d => ({...d,buffetId:''}))}>Change / unlink</button></> : matches.length === 1 ? <><strong>Possible match on the map</strong><span>{matches[0].name} · {matches[0].city}, {matches[0].state} · {matches[0].address}</span><button type="button" onClick={() => choose(matches[0])}>This is the buffet</button></> : <span>{matches.length > 1 ? 'Multiple possible matches found; enter the address to identify one.' : "Not currently on the map? That's okay. Continue with the buffet information above."}</span>}</div></fieldset>
      <fieldset><legend>Your Review</legend>{field('displayName','Display name / nickname',true)}<label className="admin-field admin-wide"><span>Rating <b>*</b></span><GoonRating rating={draft.rating} onChange={(rating) => update('rating',rating)} />{showErrors && errors.rating && <em>{errors.rating}</em>}</label><label className="admin-field admin-wide"><span>Review <b>*</b></span><textarea rows={7} maxLength={2000} value={draft.review} onChange={(e) => update('review',e.target.value)} /><small>{draft.review.trim().length} / 2,000 characters (minimum 20)</small>{showErrors && errors.review && <em>{errors.review}</em>}</label>{field('visitDate','Date visited',false,'date')}<label className="admin-field"><span>Would you return?</span><select value={draft.wouldReturn} onChange={(e) => update('wouldReturn',e.target.value as ReviewDraft['wouldReturn'])}><option value="">No answer</option><option value="yes">Yes</option><option value="no">No</option><option value="unsure">Unsure / prefer not to say</option></select></label></fieldset>
      {showErrors && !payload && <div className="form-alert" role="alert">Please correct the highlighted fields before submitting.</div>}<p className="moderation-note"><strong>Submitting will open GitHub.</strong> Sign in and click “Submit new issue” to finish posting your review.</p><div className="form-actions"><button className="secondary" type="button" onClick={clear}>Clear Form</button><button className="primary" type="submit" disabled={!payload}>Post Your Review</button></div><small className="submission-help">The site never receives GitHub credentials. Opening GitHub does not clear your saved draft or publish the review.</small></form><aside className="record-preview"><h2>Review Preview</h2>{payload ? <><h3>{payload.buffet.name}</h3><p>{payload.buffet.city}, {payload.buffet.state}<br />{payload.buffet.address}</p><p><strong>{payload.buffetId ? 'Linked to an existing map buffet' : 'Not currently linked to the map'}</strong></p><p>{payload.displayName}</p><GoonRating rating={payload.rating} /><p className="review-preview-text">{payload.review}</p>{payload.visitDate && <p>Visited: {payload.visitDate}</p>}{payload.wouldReturn && <p>Would return: {payload.wouldReturn}</p>}</> : <p>Complete the required fields to preview your review.</p>}</aside></div></main>
}
