import { mkdtemp,readFile,writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe,expect,it } from 'vitest'
import { addApprovedReview,isAuthorizedReviewApproval } from './add-approved-review.mjs'
import { extractReviewSubmission,resolveBuffet,validatePublicReview } from './review-validation.mjs'
const payload={buffet:{name:'New Buffet',address:'1 Main',city:'Town',state:'IN'},displayName:'Reviewer',rating:4,review:'This is a useful detailed review.'}
const body=`<!-- REVIEW_PUBLIC_SUBMISSION_V1\n${JSON.stringify(payload)}\nREVIEW_PUBLIC_SUBMISSION_END -->`
const event={action:'labeled',label:{name:'approved-review'},sender:{login:'GatheredApp'},issue:{body,number:123,created_at:'2026-09-05T12:00:00Z',user:{login:'real-user'}}}
describe('approved review ingestion',()=>{
 it('requires the exact trusted approval event',()=>{expect(isAuthorizedReviewApproval(event)).toBe(true);expect(isAuthorizedReviewApproval({...event,label:{name:'review-submission'}})).toBe(false);expect(isAuthorizedReviewApproval({...event,sender:{login:'random'}})).toBe(false);expect(isAuthorizedReviewApproval({...event,action:'opened'})).toBe(false)})
 it('rejects malformed, duplicate markers, unknown fields, invalid rating/state and long reviews',()=>{expect(()=>extractReviewSubmission('bad')).toThrow(/markers/);expect(()=>extractReviewSubmission(body+body)).toThrow(/Multiple/);expect(validatePublicReview({...payload,githubUser:'spoof'})).toContainEqual(expect.stringMatching(/unsupported/));expect(validatePublicReview({...payload,rating:9})).toContainEqual(expect.stringMatching(/Rating/));expect(validatePublicReview({...payload,buffet:{...payload.buffet,state:'XX'}})).toContainEqual(expect.stringMatching(/state/));expect(validatePublicReview({...payload,review:'x'.repeat(2001)})).toContainEqual(expect.stringMatching(/2,000/))})
 it('validates submitted IDs and conservatively avoids ambiguity',()=>{const b={id:'new-buffet-town-in',name:'New Buffet',address:'1 Main',city:'Town',state:'IN'};expect(resolveBuffet({...payload,buffetId:b.id},[b])).toBe(b);expect(()=>resolveBuffet({...payload,buffetId:'missing'},[b])).toThrow(/does not exist/);expect(resolveBuffet(payload,[b,{...b,id:'second'}])).toBeUndefined()})
 it('derives identity, retains unlisted reviews, and is idempotent',async()=>{const d=await mkdtemp(join(tmpdir(),'reviews-'));const ep=join(d,'event.json'),rp=join(d,'reviews.json'),bp=join(d,'buffets.json');await Promise.all([writeFile(ep,JSON.stringify(event)),writeFile(rp,'[]'),writeFile(bp,'[]')]);await addApprovedReview(ep,rp,bp);let records=JSON.parse(await readFile(rp,'utf8'));expect(records[0]).toMatchObject({id:'review-github-issue-123',githubUser:'real-user',sourceIssueNumber:123,submittedAt:event.issue.created_at});expect(records[0].buffetId).toBeUndefined();await addApprovedReview(ep,rp,bp);records=JSON.parse(await readFile(rp,'utf8'));expect(records).toHaveLength(1)})
 it('does not mutate on unauthorized event',async()=>{const d=await mkdtemp(join(tmpdir(),'reviews-'));const ep=join(d,'event.json'),rp=join(d,'reviews.json'),bp=join(d,'buffets.json');await Promise.all([writeFile(ep,JSON.stringify({...event,sender:{login:'other'}})),writeFile(rp,'[]'),writeFile(bp,'[]')]);expect(await addApprovedReview(ep,rp,bp)).toEqual({unauthorized:true});expect(await readFile(rp,'utf8')).toBe('[]')})
})
